#! /bin/bash

#DEBUG=1

launcher () {
STEAM_COMPAT_CLIENT_INSTALL_PATH=STEAMAPPS/.. STEAM_COMPAT_DATA_PATH=FF7SYW_COMPATDATA/. STEAMAPPS/common/Proton\ PROTON_VERSION/proton run FF7SYW_COMPATDATA/pfx/drive_c/Games/FF7SYWV5/TARGET_EXE &

sleep 30
while true; do
        pid_config=$(pidof "C:\Games\FF7SYWV5\FF7SYWV5\FF7_SYW_Configuration.exe")
        if [[ -z "$pid_trainer" ]]; then
                pid_trainer=$(pidof "C:\Games\FF7SYWV5\FF7SYWV5\FF7_SYW\addfiles\trainer\FF7SYWV5minitrainer.exe")
        fi
        if [[ -z "$pid_ff7" ]]; then
		pid_ff7=$(pidof "C:\Games\FF7SYWV5\FF7SYWV5\FF7_SYW\FF7_EXE")
        fi
        if [[ -z "$pid_config" ]] && [[ -z "$pid_ff7" ]]; then
                exit 0
        fi
        unset pid_config
        if [[ -n "$pid_ff7" ]]; then
                is_Z="$(grep "State:" /proc/"$pid_ff7"/status)"
                if [[ "$is_Z" =~ "Z" ]]; then
                        kill "$pid_trainer"
                        sleep 2
                        kill "$pid_ff7"
                        break
                fi
        fi
        sleep 10
done
}

if [[ -z "$DEBUG" ]]; then
	launcher
else
	set -x
	launcher 2>&1 | tee /tmp/debug_launcher
fi
